apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    template: nodejs-mongo-persistent
  name: mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi